name: API Reviewer

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Flatten current CEM
        run: |
          node ${{ github.workspace }}/.github/actions/test.cjs --file-name=flat-manifest-current
          echo "Current manifest ==="
          cat flat-manifest-current.json

      - name: Save current output file
        id: pr_file
        run: echo "::set-output name=flat-manifest-current::$(cat flat-manifest-current.json)"

      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Flatten main CEM2
        run: |
          node ${{ github.workspace }}/.github/actions/test.cjs --file-name=flat-manifest-main
          echo "Main manifest ==="
          echo "${{ steps.pr_file.outputs.current }}" > flat-manifest-current.json
          cat flat-manifest-main.json
          cat flat-manifest-current.json

