name: API Reviewer

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Flatten current CEM
      #   run: |
      #     node ${{ github.workspace }}/.github/actions/test.cjs --file-name=flat-manifest-pr
      #     echo "Current manifest ==="
      #     cat flat-manifest-pr.json

      - name: Save current output file
        id: pr_file
        run: echo "::set-output name=flat-manifest-pr::$(cat flat-manifest-pr.json)"

      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Flatten main CEM3
        run: |
          echo "Main manifest ==="
          # node ${{ github.workspace }}/.github/actions/test.cjs --file-name=flat-manifest-main
          echo "Main manifest ==="
          cat flat-manifest-main.json
          echo ""
          echo "Current manifest ==="
          echo "${{ steps.pr_file.outputs.flat-manifest-pr }}" > flat-manifest-pr.json
          cat flat-manifest-pr.json

