name: API Reviewer

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Flatten current CEM
        run: |
          node ${{ github.workspace }}/.github/actions/test.cjs --file-name=flat-manifest-current
          echo "Current manifest ==="
          cat flat-manifest-current.json

      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Flatten main CEM
        run: |
          node ${{ github.workspace }}/.github/actions/test.cjs --file-name=flat-manifest-main
          echo "Main manifest ==="
          cat flat-manifest-main.json
          cat flat-manifest-current.json
